import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Main from "./components/Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex 100vh">
          <Sidebar className="md:contents "></Sidebar> {/* A fixed sidebar */}
          <div className="lg:ml-[244px] sm:ml-[72px] pt-[22px] w-screen">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
