import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Main from "./components/Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex h-screen">
          <Sidebar className="md:contents"></Sidebar> {/* A fixed sidebar */}
          {children}
        </div>
      </body>
    </html>
  );
}
